### ISSUE TITLE
check https certificate install confluence 5.8.2

### ISSUE THREAD

**Issue by ektrontek** [mesilat/check-https-cert#2]
Dear Support Team, 
Would it be possible to install check https certificate plugin in confluence 5.8.2 environment? After we installed it , it show some message as shown as the attachment. How can we fix it ? Thanks a lot.
Best Regards, Anderson Hsu
![https](https://user-images.githubusercontent.com/19470763/34341040-31255dc2-e9ca-11e7-9287-7969dce5a1b9.jpg)

**Comment by mesilat** [comment]
Hi, Anderson
I am 99 percent confident that it will work however I do not have that old Confluence instance to test. Try it and let me know ;) If it works I will add the compatibility line in Atlassian Marketplace to get rid of the warning you see in your UPM.
Regards, Vladislav Babin

**Comment by ektrontek** [comment]
Thanks for your kindly reply.How can we test the plugin?Mainly we would
like confluence to run HTTPs://.

2017年12月25日 下午11:44，"Mesilat Limited" <notifications@github.com>寫道：

**Comment by mesilat** [comment]
Did you check the plugin description at https://mesilat.com/wiki/display/SLA/Check+HTTPS+Certificate+Addon?
Test it == use it ;)

**Comment by ektrontek** [comment]
Dear Support Team,
I think it's ok at confluence 5.8.2 environment.Thanks a lot.
Best Regards, Anderson Hsu

**Comment by mesilat** [comment]
Hi Anderson
Thanks for your feedback. I have updated the compatibility line to reflect compatibility with Confluence 5.8.2
Regards, Vladislav Babin
